version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: expofast_local_db
    restart: always
    ports:
      - "5434:5432" # Maps PostgreSQL's default port to localhost
    environment:
      POSTGRES_USER: admin # Default username
      POSTGRES_PASSWORD: admin # Default password
      POSTGRES_DB: expofast_local_db # Default database name
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data across container restarts
#      - ./api/db/init-script.sql # Optional: Initialize database with scripts

volumes:
  pgdata:
